### ISSUE TITLE
使用源码编译出来的插件是英文的，请问怎么修改源码才能编译出汉化的插件

### ISSUE THREAD

**Issue by reflander** [animegasan/luci-app-wolplus#1]
使用源码编译出来的插件是英文的，请问怎么修改源码才能编译出汉化的插件

**Comment by reflander** [comment]
固件使用的是immortalwrt分支【ImmortalWrt 21.02/ LuCI openwrt-21.02】，[hanwckf-immortalwrt-mt798x]

**Comment by animegasan** [comment]
All the languages ​​are here, but they had to be adapted to mine and recompiled.

https://github.com/animegasan/luci-app-wolplus/blob/a1d75997972c3cbc7ff149c5adbcac4db043f1e7/po/zh-cn/wolplus.po#L1-L23

**Comment by reflander** [comment]
源代码的wolplus.po文件“msgid”的值应该是错误的，修改这个文件的方式我已经试过了，修改之后编译出的插件还是英文的。原因没有深究，猜想可能是与luci21.02版本不兼容。
问题已经解决。办法：直接修改 luasrc/model/cbi/wolplus.lua 把translate后面的值直接修改为中文
